package qemu

import (
	"fmt"
	"net"
	"net/url"
	"os"
	"sort"
	"strings"

	"github.com/RoundpenAI/roundpen/internal/backend"
)

func memoryMBFromOpts(opts backend.CreateOpts) int {
	if opts.MemoryLimit <= 0 {
		return defaultMemoryMB
	}
	mb := int(opts.MemoryLimit / (1024 * 1024))
	if mb < 512 {
		return 512
	}
	return mb
}

func cpusFromOpts(opts backend.CreateOpts) int {
	if opts.CPULimit < 1 {
		return defaultCPUs
	}
	n := int(opts.CPULimit)
	if n < 1 {
		return 1
	}
	return n
}

func kvmAvailable() bool {
	_, err := os.Stat("/dev/kvm")
	return err == nil
}

// rewriteGuestURL rewrites control-plane loopback / wildcard listen URLs to
// the slirp host so the guest can reach roundpend / llmgw.
//
// Uses url.Parse (not string prefix replace) so a listen addr like
// 0.0.0.0:19001 cannot be glued onto http://127.0.0.1 and then partially
// rewritten into http://10.0.2.20.0.0.0:19001 (Invalid URL for Claude).
func rewriteGuestURL(v string) string {
	u, err := url.Parse(v)
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
		return v
	}
	if !guestShouldRewriteHost(u.Hostname()) {
		return v
	}
	if port := u.Port(); port == "" {
		u.Host = slirpHost
	} else {
		u.Host = net.JoinHostPort(slirpHost, port)
	}
	return u.String()
}

func guestShouldRewriteHost(host string) bool {
	switch strings.ToLower(strings.TrimSpace(host)) {
	case "localhost", "127.0.0.1", "::1", "0.0.0.0", "::":
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && (ip.IsLoopback() || ip.IsUnspecified())
}

func validAbsHTTP(raw string) bool {
	u, err := url.Parse(raw)
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") {
		return false
	}
	host := u.Hostname()
	if host == "" {
		return false
	}
	if ip := net.ParseIP(host); ip != nil {
		return true
	}
	for _, r := range host {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' {
			return true
		}
	}
	return false
}

func guestControlBase(raw string) string {
	base := rewriteGuestURL(strings.TrimRight(strings.TrimSpace(raw), "/"))
	if validAbsHTTP(base) {
		return strings.TrimRight(base, "/")
	}
	port := "19001"
	if u, err := url.Parse(raw); err == nil {
		if p := u.Port(); p != "" {
			port = p
		}
	}
	return "http://" + slirpHost + ":" + port
}

func defaultGatewayBase() string {
	for _, k := range []string{"ROUNDPEN_LLMGW_PUBLIC_URL", "ROUNDPEN_PREVIEW_PUBLIC_URL"} {
		if v := strings.TrimSpace(os.Getenv(k)); v != "" {
			return strings.TrimRight(v, "/")
		}
	}
	return "http://127.0.0.1:9527"
}

func mergeGuestEnv(opts backend.CreateOpts) map[string]string {
	env := make(map[string]string, len(opts.Env)+8)
	for k, v := range opts.Env {
		env[k] = v
	}
	base := strings.TrimRight(env["ROUNDPEN_URL"], "/")
	if base == "" {
		base = defaultGatewayBase()
	}
	base = guestControlBase(base)
	env["ROUNDPEN_URL"] = base
	if env["ANTHROPIC_BASE_URL"] == "" || !validAbsHTTP(rewriteGuestURL(env["ANTHROPIC_BASE_URL"])) {
		env["ANTHROPIC_BASE_URL"] = base + "/llmgw/anthropic"
	}
	if env["OPENAI_BASE_URL"] == "" || !validAbsHTTP(rewriteGuestURL(env["OPENAI_BASE_URL"])) {
		env["OPENAI_BASE_URL"] = base + "/llmgw/openai"
	}
	key := env["ANTHROPIC_API_KEY"]
	if key == "" {
		key = env["OPENAI_API_KEY"]
	}
	if key != "" {
		if env["ANTHROPIC_API_KEY"] == "" {
			env["ANTHROPIC_API_KEY"] = key
		}
		if env["OPENAI_API_KEY"] == "" {
			env["OPENAI_API_KEY"] = key
		}
		if env["ANTHROPIC_AUTH_TOKEN"] == "" {
			env["ANTHROPIC_AUTH_TOKEN"] = key
		}
	}
	if env["ACP_PERMISSION_MODE"] == "" {
		env["ACP_PERMISSION_MODE"] = "bypassPermissions"
	}
	if model := strings.TrimSpace(env["ANTHROPIC_MODEL"]); model != "" {
		for _, k := range []string{
			"ANTHROPIC_DEFAULT_OPUS_MODEL",
			"ANTHROPIC_DEFAULT_SONNET_MODEL",
			"ANTHROPIC_DEFAULT_HAIKU_MODEL",
			"ANTHROPIC_SMALL_FAST_MODEL",
			"CLAUDE_CODE_SUBAGENT_MODEL",
		} {
			if strings.TrimSpace(env[k]) == "" {
				env[k] = model
			}
		}
	}
	for k, v := range env {
		env[k] = rewriteGuestURL(v)
	}
	return env
}

func writeGuestEnv(path string, env map[string]string) error {
	keys := make([]string, 0, len(env))
	for k := range env {
		if k == "" {
			continue
		}
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("# generated by roundpen qemu backend — do not edit\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, env[k])
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}
